### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by snotskie** [EducationalSciences693/pyena#1]
- [ ] see generally https://github.com/lmcinnes/umap/blob/master/umap/umap_.py#L1366
- [ ] rotation and accumulation helpers, see https://pypi.org/project/multimethod/#:~:text=on%20keyword%20arguments.-,multimeta,-Use%20metaclass%3Dmultimeta
- [ ] ENA.fit: accumulate and find rotation vectors, see https://github.com/lmcinnes/umap/blob/master/umap/umap_.py#L2249
- [ ] ENA.transform: accumulate (as necessary) and apply rotation vectors, see https://github.com/lmcinnes/umap/blob/master/umap/umap_.py#L2787
- [ ] ENA.fit_transform: wrapper call of the above two
- [ ] plot: do the thing, figure out where it needs to live
